### ISSUE TITLE
Q：What does the time of Table 8 in the paper mean and how to use it?

### ISSUE THREAD

**Issue by River-Cold** [QuwsarOhi/fruitdet#1]
Dear Ohi, thanks for you excellent work！I want to reproduce fruitdet but I don't understand the meaning of time of Table 8 in the paper.
![image](https://user-images.githubusercontent.com/80696033/198833454-140da4b8-0144-47a4-981a-e546f1ccae92.png)
I searched the keyword "time" in your repo, but can't find anything about it.
Could you please explain it more explictly and instruct me how to use it in the code?I'm looking forward to your reply!

**Comment by QuwsarOhi** [comment]
Thank you for the comment. Time means the inference time of each detection model.

**Comment by River-Cold** [comment]
Oh!!! thanks for your quick reply❤I also wanna know is it performed on the cpu or gpu device?

**Comment by QuwsarOhi** [comment]
Welcome. Training and inference were done in GPU device.
